=== wouterbeek/IAAA/poem.dtd
<!DOCTYPE poem
[
  <!ELEMENT poem (phead,pbody)>
  <!ELEMENT phead (ptitle,author)>
  <!ELEMENT ptitle (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT pbody (stanza)>
  <!ELEMENT stanza (line)>
  <!ELEMENT line (#PCDATA)>
]>

=== wouterbeek/IAAA/elizabeth_bishop.xml
<?xml version="1.0" encoding="UTF-8"?>
  <?xml-stylesheet type="text/css" href="poem.css"?>
  <!DOCTYPE poem SYSTEM "poem.dtd">
  <poem>
    <phead>
      <ptitle>One Art</ptitle>
      <author>
        <first-name>Elizabeth</first-name>
        <last-name>Bishop</last-name>
      </author>
    </phead>
    <pbody>
      <stanza>
        <line>The art of losing isn't hard to master;</line>
        <line>so many things seem filled with the intent</line>
        <line>to be lost that their loss is no disaster,</line>
      </stanza>
      <stanza>
        <line>Lose something every day. Accept the fluster</line>
        <line>of lost door keys, the hour badly spent.</line>
        <line>The art of losing isn't hard to master.</line>
      </stanza>
      <stanza>
        <line>Then practice losing farther, losing faster:</line>
        <line>places, and names, and where it was you meant</line>
        <line>to travel. None of these will bring disaster.</line>
      </stanza>
      <stanza>
        <line>I lost my mother's watch. And look! my last, or</line>
        <line>next-to-last, of three loved houses went.</line>
        <line>The art of losing isn't hard to master.</line>
      </stanza>
      <stanza>
        <line>I lost two cities, lovely ones. And, vaster,</line>
        <line>some realms I owned, two rivers, a continent.</line>
        <line>I miss them, but it wasn't a disaster.</line>
      </stanza>
      <stanza>
        <line>- Even losing you (the joking voice, a gesture</line>
        <line>I love) I shan't have lied. It's evident</line>
        <line>the art of losing's not too hard to master</line>
        <line>though it may look like (Write it!) like a disaster.</line>
      </stanza>
    </pbody>
  </poem>
